Repository labring/aiproxy, pull requests merged in 2025-05, with the labels that each got.

#172 fix(web): fix token status display
  web/src/feature/token/components/TokenTable.tsx
Labels: size/XS

#173 fix(web): fix channel status display
  web/src/feature/channel/components/ChannelTable.tsx
Labels: size/XS

#174 fix(web): status display
  web/src/feature/channel/components/ChannelTable.tsx
  web/src/feature/token/components/TokenTable.tsx
Labels: size/XS

#176 fix: gemini usage
  core/relay/adaptor/gemini/main.go
Labels: size/M

#177 feat: log and summary from log create at
  core/model/batch.go
  core/model/log.go
  core/model/summary.go
  core/relay/adaptor/doc2x/html2md_test.go
Labels: size/L

#178 feat: log user and metadata and retry log table
  README.md
  README.zh.md
  core/common/config/config.go
  core/common/consume/consume.go
  core/common/consume/record.go
  core/controller/log.go
  core/controller/relay-controller.go
  core/docs/docs.go
  core/docs/swagger.json
  core/docs/swagger.yaml
  core/middleware/ctxkey.go
  core/middleware/distributor.go
  core/middleware/distributor_test.go
  core/model/batch.go
  core/model/log.go
  core/model/main.go
  core/model/option.go
  core/model/retrylog.go
Labels: size/XL

#179 feat: gemini reasoning content
  core/relay/adaptor/gemini/main.go
  core/relay/adaptor/gemini/model.go
Labels: size/S

#175 feat: support modles deployed by huggingface text-embeddings-inference
  core/model/chtype.go
  core/relay/adaptor/text-embeddings-inference/adaptor.go
  core/relay/adaptor/text-embeddings-inference/constants.go
  core/relay/adaptor/text-embeddings-inference/embeddings.go
  core/relay/adaptor/text-embeddings-inference/error.go
  core/relay/adaptor/text-embeddings-inference/rerank.go
  core/relay/adaptor/text-embeddings-inference/rerank_test.go
  core/relay/channeltype/define.go
Labels: size/XL

#180 fix: rarank ci lint
  core/relay/adaptor/text-embeddings-inference/rerank_test.go
Labels: size/L

#181 feat: embed web file
  .github/workflows/release.yml
  Dockerfile
  core/.gitignore
  core/common/config/config.go
  core/public/dist/.gitkeep
  core/public/public.go
  core/router/main.go
  core/router/static.go
Labels: size/L

#184 chore: bumo go mod
  core/controller/groupmcp-server.go
  core/controller/mcp-sse.go
  core/controller/publicmcp-server.go
  core/go.mod
  core/go.sum
  go.work.sum
  openapi-mcp/convert/convert.go
  openapi-mcp/go.mod
  openapi-mcp/go.sum
Labels: size/L

#185 feat: add claude 4 new field
  core/relay/adaptor/anthropic/adaptor.go
  core/relay/adaptor/anthropic/model.go
  core/relay/adaptor/anthropic/openai.go
  go.work.sum
Labels: size/M

#186 feat: adaptor features meta info
  core/controller/channel-billing.go
  core/controller/channel-test.go
  core/controller/channel.go
  core/controller/model.go
  core/docs/docs.go
  core/docs/swagger.json
  core/docs/swagger.yaml
  core/relay/adaptor/ali/fetures.go
  core/relay/adaptor/anthropic/fetures.go
  core/relay/adaptor/aws/adaptor.go
  core/relay/adaptor/aws/claude/adapter.go
  core/relay/adaptor/aws/llama3/adapter.go
  core/relay/adaptor/doubao/fetures.go
  core/relay/adaptor/doubaoaudio/fetures.go
  core/relay/adaptor/gemini/fetures.go
  core/relay/adaptor/geminiopenai/fetures.go
  core/relay/adaptor/interface.go
  core/relay/adaptor/jina/fetures.go
  core/relay/adaptor/minimax/fetures.go
  core/relay/adaptor/ollama/fetures.go
  core/relay/adaptor/openai/fetures.go
  core/relay/adaptor/openrouter/fetures.go
  core/relay/adaptor/text-embeddings-inference/fetures.go
  core/relay/adaptor/vertexai/adaptor.go
  core/relay/adaptor/vertexai/fetures.go
  core/relay/adaptors/register.go
  core/relay/controller/handle.go
Labels: size/L

#187 feat: claude web search tool support
  core/relay/adaptor/anthropic/model.go
  core/relay/adaptor/anthropic/openai.go
Labels: size/M

#188 feat: recovery notify stack info
  core/main.go
  core/middleware/recover.go
Labels: size/L

#189 fix: user ast node not exsit
  core/middleware/distributor.go
Labels: size/XS

#190 feat: shutdown batch update summary need retry when cache not cleand
  core/main.go
  core/model/batch.go
Labels: size/M

#191 fix: swag api path
  core/controller/channel-test.go
  core/controller/channel.go
  core/controller/dashboard.go
  core/controller/group.go
  core/controller/log.go
  core/controller/modelconfig.go
  core/controller/monitor.go
  core/controller/option.go
  core/controller/relay.go
  core/controller/token.go
  core/docs/docs.go
  core/docs/swagger.json
  core/docs/swagger.yaml
Labels: size/XL

#192 fix: chtype log filed no need convert to string
  core/middleware/auth.go
Labels: size/XS

#193 feat: embed default web redict to git repo
  core/public/public.go
  core/public/templates/index.tmpl
  core/router/static.go
Labels: size/L

#194 fix: edit image dont get request user
  core/middleware/distributor.go
Labels: size/XS

#195 feat: impl state less sse mcp server
  core/common/stateless-mcp/sse.go
  core/controller/groupmcp-server.go
  core/controller/publicmcp-server.go
Labels: size/M

#202 chore: update group model reqeuest record function
  core/controller/relay-controller.go
  core/middleware/distributor.go
Labels: size/L

#199 feat: mcp servers test api
  core/controller/embedmcp.go
  core/controller/groupmcp-server.go
  core/controller/publicmcp-server.go
  core/docs/docs.go
  core/docs/swagger.json
  core/docs/swagger.yaml
  core/embedmcp/mcpregister/init.go
  core/mcpservers/README.md
  core/mcpservers/aiproxy-openapi/openapi.go
  core/mcpservers/embedmcp.go
  core/mcpservers/mcpregister/init.go
  core/mcpservers/register.go
  core/middleware/auth.go
  core/router/api.go
Labels: size/XXL

#204 feat: mcp cache support
  core/controller/groupmcp-server.go
  core/controller/publicmcp-server.go
  core/controller/publicmcp.go
  core/model/cache.go
  core/model/group.go
  core/model/groupmcp.go
  core/model/publicmcp.go
Labels: size/L

#206 fix: remove readme config
  README.md
  README.zh.md
Labels: size/XS

#207 fix: remove readme config
  README.md
  README.zh.md
Labels: size/XS

#208 feat: channel adaptor spec config support
  core/controller/channel-billing.go
  core/controller/channel.go
  core/controller/dashboard.go
  core/controller/group.go
  core/controller/log.go
  core/controller/model.go
  core/controller/modelconfig.go
  core/controller/monitor.go
  core/controller/option.go
  core/controller/publicmcp-server.go
  core/controller/token.go
  core/middleware/log.go
  core/model/channel.go
  core/model/consumeerr.go
  core/model/group.go
  core/model/log.go
  core/model/modelconfig.go
  core/model/token.go
  core/relay/adaptor/ali/config.go
  core/relay/adaptor/anthropic/config.go
  core/relay/adaptor/cohere/model.go
  core/relay/adaptor/doc2x/config.go
  core/relay/adaptor/gemini/config.go
  core/relay/adaptor/gemini/main.go
  core/relay/adaptor/interface.go
  core/relay/adaptor/openai/config.go
  core/relay/adaptor/text-embeddings-inference/rerank_test.go
  core/relay/adaptor/vertexai/config.go
  core/relay/adaptors/register.go
  core/relay/controller/dohelper.go
  core/relay/model/completions.go
Labels: size/XL

#213 fix: redis group model config map need type equal to map
  core/model/cache.go
  core/model/group.go
Labels: size/S

#214 fix: gemini embed usage
  core/relay/adaptor/gemini/embeddings.go
Labels: size/XS

#218 feat: cache plugin support redis store
  core/controller/relay-controller.go
  core/relay/plugin/cache/README.md
  core/relay/plugin/cache/README.zh.md
  core/relay/plugin/cache/cache.go
  core/relay/plugin/cache/config.go
Labels: size/L

#220 fix: skip cache when request or response is empty
  core/relay/plugin/cache/cache.go
Labels: size/XS

#222 chore: rename redis conn str
  README.md
  README.zh.md
  core/common/redis.go
  core/deploy/Kubefile
  core/deploy/manifests/aiproxy-config.yaml.tmpl
  docker-compose.yaml
Labels: size/S

#223 feat: searchxng web search support
  core/relay/plugin/web-search/README.md
  core/relay/plugin/web-search/README.zh.md
  core/relay/plugin/web-search/config.go
  core/relay/plugin/web-search/search.go
  mcp-servers/web-search/README.md
  mcp-servers/web-search/engine/searchxng.go
  mcp-servers/web-search/engine/types.go
  mcp-servers/web-search/features.md
  mcp-servers/web-search/server.go
Labels: size/L

#226 feat: streamable http mcp server proxy support use sse endpoint to request
  core/.golangci.yml
  core/common/balance/sealos.go
  core/common/mcpproxy/sse.go
  core/common/mcpproxy/sse_test.go
  core/common/mcpproxy/streamable.go
  core/common/stateless-mcp/sse.go
  core/controller/embedmcp.go
  core/controller/groupmcp-server.go
  core/controller/publicmcp-server.go
  core/controller/relay-controller.go
  core/docs/docs.go
  core/docs/swagger.json
  core/docs/swagger.yaml
  core/middleware/auth.go
  core/model/cache.go
  core/model/token.go
  mcp-servers/.golangci.yml
  openapi-mcp/.golangci.yml
Labels: size/XXL

#227 feat: sse mcp backend support proxy to streamable http
  core/common/mcpproxy/server.go
  core/common/mcpproxy/sse.go
  core/common/mcpproxy/stateless-streamable.go
  core/common/mcpproxy/streamable.go
  core/controller/embedmcp.go
  core/controller/groupmcp-server.go
  core/controller/publicmcp-server.go
  core/router/static.go
Labels: size/XL
