Repository labring/aiproxy, pull requests merged in 2025-03, with the labels that each got.

#6 feat: log downstream result support
  common/consume/consume.go
  controller/channel-test.go
  controller/relay.go
  middleware/distributor.go
  model/log.go
  model/utils.go
  relay/adaptor/anthropic/main.go
  relay/adaptor/aws/llama3/main.go
  relay/adaptor/baidu/main.go
  relay/adaptor/cohere/main.go
  relay/adaptor/coze/main.go
  relay/adaptor/gemini/main.go
  relay/adaptor/ollama/main.go
  relay/constant/common.go
  relay/constant/finishreason/define.go
  relay/constant/role/define.go
  relay/controller/consume.go
  relay/controller/handle.go
  relay/controller/image.go
  relay/controller/pdf.go
  relay/controller/rerank.go
  relay/controller/stt.go
  relay/controller/text.go
  relay/controller/tts.go
  relay/meta/meta.go
  relay/model/constant.go
Labels: size/L

#7 feat: get channel from header
  controller/relay.go
  relay/controller/handle.go
Labels: size/M

#8 fix: vertexai key format
  .github/workflows/ci.yml
  relay/adaptor/doubaoaudio/tts.go
  relay/adaptor/vertexai/claude/adapter.go
  relay/adaptor/vertexai/gemini/adapter.go
  relay/adaptor/vertexai/key.go
  relay/adaptor/vertexai/registry.go
Labels: size/L

#10 fix: even non downstream result need to record channel data
  model/utils.go
Labels: size/M

#11 feat: channel designated
  common/ctxkey/key.go
  controller/relay.go
  middleware/auth.go
  middleware/distributor.go
  model/cache.go
  model/channel.go
Labels: size/L

#13 fix: miss record when prepare retry
  controller/relay.go
Labels: size/M

#16 feat: vertexai claude think support
  relay/adaptor/anthropic/model.go
  relay/adaptor/vertexai/claude/adapter.go
  relay/adaptor/vertexai/claude/model.go
Labels: size/S

#17 fix: clean lock filed use cad
  common/trylock/lock.go
Labels: size/S

#14 feat: aliyun registry
  .github/workflows/release.yml
Labels: size/M

#18 fix: repeated push tag
  .github/workflows/release.yml
Labels: size/S

#19 feat: ollama tool call
  relay/adaptor/ollama/adaptor.go
  relay/adaptor/ollama/main.go
  relay/adaptor/ollama/model.go
  relay/adaptor/openai/main.go
  relay/model/tool.go
Labels: size/L

#20 fix: ali stt realtime
  relay/adaptor/ali/stt-realtime.go
Labels: size/M

#21 fix: ali rerank model
  relay/adaptor/ali/rerank.go
  relay/model/rerank.go
Labels: size/S

#23 fix: claude handle balance error
  main.go
  relay/adaptor/anthropic/error.go
  relay/adaptor/anthropic/main.go
  relay/adaptor/openai/token.go
Labels: size/M

#26 feat: baiduv2 rerank
  relay/adaptor/baiduv2/adaptor.go
Labels: size/XS

#27 fix: baidu token expr
  relay/adaptor/baidu/token.go
  relay/adaptor/baiduv2/adaptor.go
  relay/adaptor/baiduv2/token.go
  relay/adaptor/vertexai/adaptor.go
  relay/adaptor/vertexai/token.go
Labels: size/L

#28 fix: need write status code when context done
  controller/relay.go
Labels: size/XS

#30 feat: log query result only
  controller/dashboard.go
  controller/log.go
  model/log.go
Labels: size/M

#31 feat: gemini image
  relay/adaptor/gemini/main.go
  relay/adaptor/gemini/model.go
  relay/adaptor/openai/main.go
Labels: size/L

#33 feat: cache token billing support
  README.md
  README.zh.md
  common/consume/consume.go
  controller/relay.go
  middleware/distributor.go
  model/log.go
  model/modelconfig.go
  model/utils.go
  relay/adaptor/anthropic/main.go
  relay/adaptor/anthropic/model.go
  relay/adaptor/openai/main.go
  relay/adaptor/openai/model.go
  relay/adaptor/openai/stt.go
  relay/controller/consume.go
  relay/controller/dohelper.go
  relay/controller/handle.go
  relay/controller/price.go
  relay/controller/rerank.go
  relay/controller/stt.go
  relay/controller/text.go
  relay/controller/tts.go
  relay/model/general.go
  relay/model/misc.go
Labels: size/L

#35 fix: readme
  README.md
  README.zh.md
Labels: size/XS

#36 fix: clean modeltype and clean no used package
  common/ctxkey/key.go
  common/random/main.go
  controller/relay.go
  controller/token.go
  main.go
  middleware/auth.go
  middleware/ctxkey.go
  middleware/distributor.go
  middleware/reqid.go
  model/token.go
  relay/adaptor/anthropic/main.go
  relay/adaptor/aws/claude/main.go
  relay/adaptor/aws/llama3/main.go
  relay/adaptor/baidu/main.go
  relay/adaptor/cohere/adaptor.go
  relay/adaptor/cohere/main.go
  relay/adaptor/coze/main.go
  relay/adaptor/coze/model.go
  relay/adaptor/gemini/adaptor.go
  relay/adaptor/gemini/embeddings.go
  relay/adaptor/gemini/main.go
  relay/adaptor/ollama/main.go
  relay/adaptor/openai/id.go
  relay/adaptor/openai/moderations.go
  relay/adaptor/vertexai/gemini/adapter.go
  relay/model/constant.go
Labels: size/L

#37 fix: parse pdf price
  relay/controller/pdf.go
Labels: size/S

#39 fix: dependabot no need push image
  .github/workflows/release.yml
Labels: size/S

#40 docs: update tiktoken readme
  README.md
  README.zh.md
Labels: size/XS

#42 chore: update azure default api version
  relay/adaptor/azure/key.go
Labels: size/XS

#41 fix: exclude tests model
  common/consume/consume.go
  controller/channel-test.go
  middleware/auth.go
  middleware/distributor.go
  model/channel.go
  model/channeltest.go
  model/modelconfig.go
  relay/adaptor/ali/adaptor.go
  relay/adaptor/ali/constants.go
  relay/controller/consume.go
  relay/controller/handle.go
  relay/meta/meta.go
Labels: size/L

#43 refactor: rpm mem limit and limit header
  common/rpmlimit/mem.go
  common/rpmlimit/rate-limit.go
  common/rpmlimit/redis.go
  middleware/distributor.go
Labels: size/XL

#44 feat: open router reasioning to reasoning_content
  controller/import.go
  relay/adaptor/openai/adaptor.go
  relay/adaptor/openai/main.go
  relay/adaptor/openrouter/adaptor.go
  relay/channeltype/define.go
Labels: size/L

#46 feat: Add logic to check for direct matching model names
  relay/adaptor/xunfei/adaptor.go
  relay/adaptor/xunfei/main.go
Labels: size/S

#48 feat: custom listen addr
  main.go
Labels: size/S

#49 docs: update listen readme
  README.md
  README.zh.md
Labels: size/XS

#52 fix: check gemini has image
  relay/adaptor/gemini/main.go
Labels: size/S

#55 fix: price and usage typed
  common/consume/consume.go
  common/consume/record.go
  controller/channel-test.go
  controller/modelconfig.go
  controller/relay-controller.go
  controller/token.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  middleware/auth.go
  middleware/distributor.go
  middleware/utils.go
  model/log.go
  model/modelconfig.go
  model/token.go
  model/utils.go
  relay/adaptor/ali/constants.go
  relay/adaptor/anthropic/constants.go
  relay/adaptor/baichuan/constants.go
  relay/adaptor/baidu/constants.go
  relay/adaptor/baiduv2/constants.go
  relay/adaptor/deepseek/constants.go
  relay/adaptor/doc2x/constants.go
  relay/adaptor/doubao/constants.go
  relay/adaptor/doubaoaudio/constants.go
  relay/adaptor/gemini/constants.go
  relay/adaptor/lingyiwanwu/constants.go
  relay/adaptor/minimax/constants.go
  relay/adaptor/moonshot/constants.go
  relay/adaptor/openai/constants.go
  relay/adaptor/openai/token.go
  relay/adaptor/openai/util.go
  relay/adaptor/siliconflow/constants.go
  relay/adaptor/stepfun/constants.go
  relay/adaptor/tencent/constants.go
  relay/adaptor/xai/constants.go
  relay/adaptor/xunfei/constants.go
  relay/adaptor/zhipu/constants.go
  relay/controller/chat.go
  relay/controller/completions.go
  relay/controller/consume.go
  relay/controller/dohelper.go
  relay/controller/embed.go
  relay/controller/handle.go
  relay/controller/image.go
  relay/controller/pdf.go
  relay/controller/price.go
  relay/controller/rerank.go
  relay/controller/stt.go
  relay/controller/text.go
  relay/controller/tts.go
  relay/meta/meta.go
Labels: size/XXL

#57 feat: channel group sets support
  controller/channel.go
  controller/dashboard.go
  controller/group.go
  controller/model.go
  controller/relay-controller.go
  controller/relay-model.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  middleware/auth.go
  middleware/distributor.go
  model/cache.go
  model/channel.go
  model/group.go
  router/api.go
Labels: size/XL

#58 feat: full swat params
  controller/channel-test.go
  controller/dashboard.go
  controller/group.go
  controller/log.go
  controller/modelconfig.go
  controller/monitor.go
  controller/option.go
  controller/token.go
  controller/utils.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  model/consumeerr.go
  router/api.go
Labels: size/XXL

#59 fix: add group token swag query docs
  controller/token.go
Labels: size/XS

#60 fix: rpm detail group can be empty
  common/rpmlimit/mem.go
  common/rpmlimit/redis.go
  controller/dashboard.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: size/M

#61 fix: dashboard rpm detail from cache
  controller/dashboard.go
  controller/log.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  model/log.go
  router/api.go
Labels: size/XL

#63 feat: claude more tool type support
  relay/adaptor/anthropic/adaptor.go
  relay/adaptor/anthropic/main.go
  relay/adaptor/anthropic/model.go
Labels: size/M

#64 feat: basic aiproxy http handler
  router/main.go
Labels: size/XS

#65 fix: vertex ai claude stream mode dosnot resp input usage
  relay/adaptor/anthropic/main.go
Labels: size/M

#68 feat: vertexai claude cache usage
  relay/adaptor/anthropic/error.go
  relay/adaptor/anthropic/main.go
  relay/controller/dohelper.go
  relay/model/misc.go
Labels: size/L

#69 feat: dashboard token usage
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  model/log.go
Labels: size/L

#70 feat: group model config
  common/conv/any.go
  controller/dashboard.go
  controller/group.go
  controller/relay-controller.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  middleware/distributor.go
  model/cache.go
  model/group.go
  model/groupmodel.go
  model/log.go
  model/main.go
  model/modelconfig.go
  model/token.go
  relay/adaptor/anthropic/main.go
  relay/adaptor/anthropic/model.go
  relay/adaptor/baidu/main.go
  relay/adaptor/cohere/main.go
  relay/adaptor/coze/main.go
  relay/adaptor/gemini/main.go
  relay/adaptor/minimax/tts.go
  relay/adaptor/ollama/main.go
  relay/adaptor/openai/main.go
  relay/model/tool.go
  router/api.go
Labels: size/XXL

#71 chore: optimize log sql
  model/log.go
Labels: size/L

#73 feat: record ttfb
  common/consume/consume.go
  common/consume/record.go
  controller/relay-controller.go
  middleware/ctxkey.go
  middleware/distributor.go
  middleware/reqid.go
  model/log.go
  model/utils.go
  relay/controller/dohelper.go
  relay/controller/handle.go
  relay/meta/meta.go
Labels: size/L

#74 feat: clean db index
  model/log.go
Labels: size/M

#75 chore: swag init
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: size/S

#76 feat: clean log content
  README.md
  README.zh.md
  common/config/config.go
  common/trunc.go
  model/log.go
  model/option.go
  model/utils.go
Labels: size/L

#77 feat: channels param
  .github/workflows/release.yml
  Dockerfile
  controller/dashboard.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  model/channel.go
  model/log.go
  scripts/swag.sh
  scripts/tiktoken.sh
Labels: size/L

#79 feat: detech ip groups and block
  README.md
  README.zh.md
  common/config/config.go
  common/ipblack/main.go
  common/ipblack/mem.go
  common/ipblack/redis.go
  common/rpmlimit/main.go
  common/rpmlimit/redis.go
  controller/group.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
  middleware/ipblack.go
  model/group.go
  model/log.go
  model/option.go
  router/api.go
  router/relay.go
Labels: size/XL

#80 readme: update usage
  README.md
  README.zh.md
Labels: size/M

#81 fix: remove rpm tpm group filed
  middleware/distributor.go
  model/cache.go
  model/group.go
Labels: size/M

#82 feat: sum dashboard response
  model/log.go
Labels: size/M

#83 feat: dashboard timestamp query
  controller/dashboard.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
Labels: size/L

#85 feat: async create log index
  model/main.go
Labels: size/S

#86 fix: clean log use subquery limit
  model/log.go
Labels: size/S

#87 fix: remove time trunc by day
  model/log.go
Labels: size/M

#89 perf: optimize clean log content perf
  controller/dashboard.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  model/log.go
Labels: size/M

#90 feat: clean log batch size
  README.md
  README.zh.md
  common/config/config.go
  main.go
  model/log.go
  model/option.go
Labels: size/S

#91 perf: log index donot include reqid
  controller/log.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  model/log.go
Labels: size/L

#92 fix: content clean sql
  README.md
  README.zh.md
  common/config/config.go
  main.go
  model/log.go
Labels: size/S

#93 fix: clean not do not concurrent
  README.md
  README.zh.md
  main.go
  model/log.go
Labels: size/S

#94 fix: pgsql string agg groupid
  main.go
  model/log.go
Labels: size/S

#97 tryfix: setup header error code 401
  relay/adaptor/vertexai/token.go
  relay/controller/dohelper.go
Labels: size/S

#98 feat: channel type name
  common/consume/record.go
  controller/channel-billing.go
  controller/channel-test.go
  controller/relay-controller.go
  middleware/auth.go
  relay/channeltype/define.go
  relay/controller/dohelper.go
  relay/controller/handle.go
  relay/meta/meta.go
Labels: size/L

#99 feat: relay mode check
  controller/relay-controller.go
  middleware/distributor.go
  model/log.go
Labels: size/M

#100 fix: sealos balance update
  common/balance/sealos.go
Labels: size/S

#95 feat: summary table
  common/consume/consume.go
  controller/dashboard.go
  controller/log.go
  controller/relay-controller.go
  main.go
  model/batch.go
  model/groupsummary.go
  model/log.go
  model/main.go
  model/summary.go
  model/utils.go
  relay/adaptor/ali/rerank.go
  relay/adaptor/ali/stt-realtime.go
  relay/adaptor/ali/tts.go
  relay/adaptor/anthropic/model.go
  relay/adaptor/aws/llama3/model.go
  relay/adaptor/baidu/image.go
  relay/adaptor/cohere/model.go
  relay/adaptor/doc2x/pdf.go
  relay/adaptor/gemini/main.go
  relay/adaptor/minimax/tts.go
  relay/adaptor/ollama/model.go
  relay/adaptor/openai/helper.go
  relay/adaptor/openai/image.go
  relay/adaptor/openai/main.go
  relay/adaptor/openai/stt.go
  relay/adaptor/openai/token.go
  relay/adaptor/siliconflow/adaptor.go
  relay/controller/image.go
  relay/controller/rerank.go
  relay/controller/stt.go
  relay/controller/tts.go
  relay/meta/meta.go
  relay/model/misc.go
  relay/model/pdf.go
  relay/model/rerank.go
Labels: size/XXL

#102 fix: empty time
  model/groupsummary.go
Labels: size/XS
